---
#Ttree:
#  ContentRepositoryImporter:
#    presets:
#      'base':
#        'news':
#          label: 'News Import'
#          dataProviderClassName: 'Your\Package\Importer\DataProvider\NewsDataProvider'
#          importerClassName: 'Your\Package\Importer\Importer\NewsImporter'
#
#        'page':
#          label: 'Page Import'
#          dataProviderClassName: 'Your\Package\Importer\DataProvider\PageDataProvider'
#          importerClassName: 'Your\Package\Importer\Importer\PageImporter'
#          batchSize': 120
#
#        'pageContent':
#          label: 'Page Content Import'
#          dataProviderClassName: 'Your\Package\Importer\DataProvider\PageContentDataProvider'
#          importerClassName: 'Your\Package\Importer\Importer\PageContentImporter'
#          batchSize: 120