Ttree:
  ContentRepositoryImporter:
#    presets:
#      'base':
#        - 'label': 'News Import'
#          'dataProviderClassName': 'Your\Package\Importer\DataProvider\NewsDataProvider'
#          'importerClassName': 'Your\Package\Importer\Importer\NewsImporter'
#
#        - 'label': 'Page Import'
#          'dataProviderClassName': 'Ttree\ArchitectesCh\Importer\DataProvider\PageDataProvider'
#          'importerClassName': 'Ttree\ArchitectesCh\Importer\Importer\PageImporter'
#          'batchSize': 120
#
#        - 'label': 'Page Content Import'
#          'dataProviderClassName': 'Ttree\ArchitectesCh\Importer\DataProvider\PageContentDataProvider'
#          'importerClassName': 'Ttree\ArchitectesCh\Importer\Importer\PageContentImporter'
#          'batchSize': 120